# Configurações do GitHub Pages
# Configuração para desativar o Jekyll
theme: jekyll-theme-cayman
include: [""]
# Configurações de build
auto: true
# Configurações de caminho
baseurl: "" # Pode ser deixado vazio se for a raiz do domínio
url: "" # Pode ser deixado vazio para usar o domínio padrão do GitHub Pages
# Configurações de metadados
title: Portfólio de Marcelo Silva
description: Portfólio profissional mostrando meus projetos e habilidades
author: Marcelo Silva
# Configurações de plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
# Configurações de build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
  - .gitignore
  - .git/
  - .vscode/
  - .idea/
  - .DS_Store
  - Thumbs.db
  - .sass-cache/
  - _site/
  - .jekyll-cache/
